# Generated by Django 4.0.6 on 2023-02-17 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('activated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Csv',
            },
        ),
        migrations.CreateModel(
            name='CovertedToDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monitering_Date', models.DateField(blank=True, null=True)),
                ('Circle', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Component', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Hour', models.IntegerField(blank=True, null=True)),
                ('Total_Customers', models.IntegerField(blank=True, null=True)),
                ('Anomal', models.CharField(blank=True, max_length=100, null=True)),
                ('Ratio_Date', models.IntegerField(blank=True, null=True)),
                ('Ratio_Voice', models.IntegerField(blank=True, null=True)),
                ('Ratio_HSI', models.IntegerField(blank=True, null=True)),
                ('cluster_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('Data_Volume', models.IntegerField(blank=True, null=True)),
                ('Data_Volume_Formula', models.IntegerField(blank=True, null=True)),
                ('Data_Volume_mean', models.IntegerField(blank=True, null=True)),
                ('Data_Volume_std', models.IntegerField(blank=True, null=True)),
                ('Voice_Affected_Users', models.IntegerField(blank=True, null=True)),
                ('Voice_Affected_Users_Formula', models.IntegerField(blank=True, null=True)),
                ('Voice_Affected_Users_mean', models.IntegerField(blank=True, null=True)),
                ('Voice_Affected_Users_std', models.IntegerField(blank=True, null=True)),
                ('HSI_Affected_Users', models.IntegerField(blank=True, null=True)),
                ('HSI_Affected_Users_Formula', models.IntegerField(blank=True, null=True)),
                ('HSI_Affected_Users_mean', models.IntegerField(blank=True, null=True)),
                ('HSI_Affected_Users_std', models.IntegerField(blank=True, null=True)),
                ('Data_Change', models.FloatField(blank=True, null=True)),
                ('Voice_Change', models.FloatField(blank=True, null=True)),
                ('HSI_Change', models.FloatField(blank=True, null=True)),
                ('num_grids', models.IntegerField(blank=True, null=True)),
                ('num_cells', models.IntegerField(blank=True, null=True)),
                ('num_sectors', models.IntegerField(blank=True, null=True)),
                ('Indoor_Freqency_850', models.IntegerField(blank=True, null=True)),
                ('Indoor_Freqency_1800', models.IntegerField(blank=True, null=True)),
                ('Indoor_Freqency_2300', models.IntegerField(blank=True, null=True)),
                ('prb_20', models.IntegerField(blank=True, null=True)),
                ('prb_70_90', models.IntegerField(blank=True, null=True)),
                ('prb_90', models.IntegerField(blank=True, null=True)),
                ('prb_20_per', models.FloatField(blank=True, null=True)),
                ('prb_70_90_per', models.FloatField(blank=True, null=True)),
                ('prb_90_per', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('total_users_data_complaints', models.IntegerField(blank=True, null=True)),
                ('total_users_vvm_complaints', models.IntegerField(blank=True, null=True)),
                ('total_users_covergae_complaints', models.IntegerField(blank=True, null=True)),
                ('total_users_other_complaints', models.IntegerField(blank=True, null=True)),
                ('totla_upc_generated', models.IntegerField(blank=True, null=True)),
                ('Polygon', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CovertedToDB',
            },
        ),
    ]
